name: Continuous Integration

on: push

jobs:
  build-app:
    name: Build app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run bundle

  build-redis-stunnel:
    name: Build redis-stunnel Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: false
          tags: osrecki/redis-stunnel:latest
